Added form to add a new city, added banner to the form, tested it
shanlon800/weather-review pull request #15
Opened 2018-01-26 16:39 UTC by sfrunza

I added a add new city form and also added a column "banner" in the city migration
wrote tests for the form

2018-01-26 16:44 UTC, sfrunza commented
Hey Dan we get this migration failing message from Codeship, im not really sure how to fix it

2018-01-26 18:17 UTC, dpickett requested changes

2018-01-26 18:17 UTC, dpickett commented on app/controllers/cities_controller.rb
> +      flash[:notice] = "You need to be signed in to add a City."
good!

2018-01-26 18:17 UTC, dpickett commented on app/controllers/cities_controller.rb
> +    unless user_signed_in?
we should only run the conditional below *if* the user is signed in. Execution will not stop on the `redirect`

2018-01-26 18:17 UTC, dpickett commented on spec/features/user_can_add_a_city.rb
> +  end
we should also have a scenario where a signed out user cannot add a city.

2018-01-26 18:17 UTC, dpickett commented on spec/features/user_can_add_a_city.rb
> +    after do
this test does not assert anything.

2018-01-30 20:53 UTC, sfrunza commented
made some changes in CityTile test file and added package-lock and yarn

2018-01-30 21:13 UTC, sfrunza commented
deleted the picture

2018-01-30 21:16 UTC, merged