Created voting table migration, model and updates API endpoints and test
shanlon800/weather-review pull request #17
Opened 2018-01-26 19:20 UTC by acambece

Dan:

Here's the changelog:
- Created migration for vote tables
- Updated associations for Reviews, Cities, Users and votes via models
- Updated tests to confirm returned json data

Thanks!

2018-01-30 18:20 UTC, nwalberts commented on app/controllers/api/v1/reviews_controller.rb
>  end
this is a bit janky, and needs refactoring. Constructing your own hash like this is very tedious, and using a JSON serializer is preferred. You should also consider a private method or two at the bottom of this file to help organize it and set the upvote and downvote correctly.

2018-01-30 18:23 UTC, nwalberts commented on app/controllers/api/v1/reviews_controller.rb
>  end
You also should utilize your activerecord associations to grab the correct reviews for the city in question

2018-01-30 18:24 UTC, nwalberts commented on app/controllers/api/v1/users_controller.rb
> -
Same thing here, needs a good deal of refactoring here. Use a serializer

2018-01-30 18:25 UTC, nwalberts commented on app/models/user.rb
>    # Include default devise modules. Others available are:
The second two has_many associations should not need the `through` keywords. 
E.g. there is a direct relationship between a user and a review, so the through keyword is not needed

2018-01-30 18:27 UTC, nwalberts commented on db/migrate/20180126150047_create_vote_system.rb
> +      t.boolean :vote
While not required, I would strongly suggesting avoiding a boolean for an attribute that can have three values (upvoted, downvoted, or not voted). `nil` as a value can lead to errors and bugs.

2018-01-31 20:16 UTC, dpickett requested changes

2018-01-31 20:16 UTC, dpickett commented on app/models/review.rb
> +  def upvotes
if you define this routine in the model, you do not need to duplicate it in the correlating serializer. You should be able to define these methods once.

2018-01-31 20:43 UTC, dpickett approved these changes

2018-01-31 20:43 UTC, merged