Added user edit page, avatar to user and tests to it
shanlon800/weather-review pull request #8
Opened 2018-01-24 18:03 UTC by sfrunza

Hey i have the nav bar ready with some updates, please pull it

2018-01-24 19:42 UTC, bkincart requested changes

2018-01-24 19:42 UTC, bkincart commented on app/javascript/packs/application.js
> +console.log('Hello World from Webpacker')
I don't think you want to delete the work from yesterday here, correct? Please be sure to run the following to fix this and re-push:
```
git checkout master
git pull origin master
git checkout nav-bar
git merge master
```

2018-01-24 19:42 UTC, bkincart commented on app/views/devise/registrations/edit.html.erb
> +
Nice conditional view!

2018-01-24 19:42 UTC, bkincart commented on spec/features/user_edit_profile_spec.rb
> +    click_button 'Update'
Could we add an expectation that the field is there to upload an avatar?

2018-01-25 15:15 UTC, sfrunza commented
hey my tests are passing! please take a look

2018-01-25 15:21 UTC, dpickett approved these changes

2018-01-25 15:21 UTC, dpickett commented on app/javascript/packs/application.js
> +console.log('You\'re doing great!')
we should eliminate any `console.log` or `binding.pry` statements prior to pull requesting.

2018-01-25 15:21 UTC, merged